OBJS = src\main.cpp 

CC = g++

INCLUDE_PATHS = -IC:\OpenGl\glfw-3.3.2.bin.WIN32\include -IC:\OpenGl\glew-2.1.0\include

LIBRARY_PATHS = -LC:\OpenGl\glfw-3.3.2.bin.WIN32\lib-mingw -LC:\OpenGl\glew-2.1.0\lib\Release\Win32

COMPILER_FLAGS = -w -Wl, -subsystem,windows -

LINKER_FLAGS = -lglfw3dll -lglew32 -lOpenGL32 -lglu32

OBJ_NAME = Terreno

all : $(OBJS)
	$(CC) $(OBJS) $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(CONPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)

